name: Rust semver-checks

on:
  # Allow this workflow to be called by another workflow
  workflow_call:
    inputs:
      baseline-rev:
        description: "The base rev to compare against. Defaults to the PR's base branch."
        type: string
        required: false
      apt-dependencies:
        description: "A list of space-separated apt dependencies to install before running."
        type: string
        default: ""
        required: false
    secrets:
      GITHUB_PAT:
        description: "The github token for the user that will post comments."
        required: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  semver-checks:
    name: Rust semver-checks ðŸ¦€
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    steps:
      - name: Install apt dependencies
        if: ${{ inputs.apt-dependencies != '' }}
        run: |
          echo "Installing apt dependencies: $APT_DEPENDENCIES"
          sudo apt-get install -y $APT_DEPENDENCIES
        env:
          APT_DEPENDENCIES: ${{ inputs.apt-dependencies }}
      - uses: quantinuum/hugrverse-actions/rs-semver-checks@main
        with:
          baseline-rev: ${{ inputs.baseline-rev }}
          token: ${{ secrets.GITHUB_PAT }}
